export const categorydata=[
    ["Appliances",["Tv",["Fridge",["Vertical"]]]],
    ["Health",["AccuBP checker","ThermoMeters","Tablets"]],
    ["Education",["Books","NoteBooks"]],
    ["Business",["Deal","Office"]],
    ["Automobiles",["Cars","Commertial Vehicles","Luxury Cars","Heavy Transport Vehicle","Spare Parts","Other Vehicles"]],
    ["Clothing",["Shirts","Jeans"]],
    ["Electronics",["Mobiles","EarPhones"]],
    ["Furniture",["Table","Chair","SofaSet"]],
    ["Jobs",["Online Jobs","Freelancing","Part Time"]],
    ["Phones",["Samsung","Apple","Huawei"]],
    ["Services",["Cleaning","Laundry","Electrician"]],
    ["Realestate",["Rent","Buy","Commercial"]],
    ["Animals",["Dogs","Cats","Other"]],
    ["Laptops",["Dell","Lenovo","Hp"]],
    ["Community",["Sectery","Other"]],
    ["Personals",["Guard","Gardener","Other"]],
    ["Travel",["Hotels","Tours","Transport"]],
    ["Intetnet",["Packages","Routers","Other"]]

]
export const categoriesimg=[
    ["Appliances",require('../../../assets/AppIcons/Appliances.png')],
    ["Health",require('../../../assets/AppIcons/Health.png')],
    ["Education",require('../../../assets/AppIcons/Education.png')],
    ["Business",require('../../../assets/AppIcons/Business.png')],
    ["Automobiles",require('../../../assets/AppIcons/Automobile.png')],
    ["Clothing",require('../../../assets/AppIcons/Clothes.png')],
    ["Electronics",require('../../../assets/AppIcons/Electronics.png')],
    ["Furniture",require('../../../assets/AppIcons/Furniture.png')],
    ["Jobs",require('../../../assets/AppIcons/Jobs.png')],
    ["Phones",require('../../../assets/AppIcons/Phones.png')],
    ["Services",require('../../../assets/AppIcons/Services.png')],
    ["Realestate",require('../../../assets/AppIcons/Realestate.png')],
    ["Animals",require('../../../assets/AppIcons/Animals.png')],
    ["Laptops",require('../../../assets/AppIcons/Laptop.png')],
    ["Community",require('../../../assets/AppIcons/Community.png')],
    ["Personals",require('../../../assets/AppIcons/Personals.png')],
    ["Travel",require('../../../assets/AppIcons/Travels.png')],
    ["Intetnet",require('../../../assets/AppIcons/Internet.png')]
]